### ISSUE TITLE
Run with docker

### ISSUE THREAD

**Issue by mikeS7** [bartbutenaers/node-red-contrib-vcgencmd#2]
link to my previous issue #1 , to run with docker  suggestion from domoticz can be used [link](https://github.com/fchauveau/rpi-domoticz-docker#pro-tips)
Could you please update readme

**Comment by bartbutenaers** [comment]
Hi @mikeS7,
Can you expain this with a bit more detail?  Is thus an alternative approach for you other proposal?

[EDIT]  And what do you want to be added to my readme file?

Bart

**Comment by mikeS7** [comment]
It's just a simple way to run your node under docker.
I'm asking you to add the [link to method to run vcgencmd under docker](https://github.com/fchauveau/rpi-domoticz-docker#pro-tips)

**Comment by bartbutenaers** [comment]
Hi Mike,
Thanks for pointing this out!!
I have added a Docker related [section](https://github.com/bartbutenaers/node-red-contrib-vcgencmd/blob/master/README.md#usage-via-docker) to the readme file.  Could you please review it, and let me know if all ok.

**Comment by mikeS7** [comment]
Hi Bart,
it's not a my solution, will be better to add a link to the source which I provided.

**Comment by bartbutenaers** [comment]
Hey Mike,
You are too modest ;-)
I have rewritten the readme section.  Is it better now?
Have no other issues left, so if it works for you on Docker I will publish the first version on NPM ...

**Comment by mikeS7** [comment]
Thanks, it's passed my quick test )

**Comment by TheNON75** [comment]
Hi @bartbutenaers,

I am running nodered in docker on a pi and have implemented the setting based on the readme, but still does not work for me.
The node status in the flow appears like "not supported". 
When I try to run the command (taken from the vcgencmd node) with exec node, it throws an error:
"Command failed: /opt/vc/bin/vcgencmd measure_temp 1597760589114/bin/bash: /opt/vc/bin/vcgencmd: No such file or directory"

current docker settings:
`                "Source": "/opt/vc",
                "Destination": "/opt/vc",
                "LD_LIBRARY_PATH=/opt/vc/lib",`

may you pls check what could be wrong?

Thanks in advance

**Comment by mikeS7** [comment]
@TheNON75 
Readme should be updated ;)
[solved](https://discourse.nodered.org/t/use-vcgencmd-within-a-docker-node-red-container/23050/11?u=mikes7)

**Comment by TheNON75** [comment]
Thanks for the info, so far I have no clue about what to do with it or how to. Hope I'll be able to solve it, but a readme update would be great indeed

How temporary is the solution? Next docker restart or pulling a new image?

**Comment by bartbutenaers** [comment]
Hey @mikeS7,
Thanks for the support!  I don't use Docker myself for Node-RED.  But if you could be so kind to let me know what to put on the readme, then I will update it.
Bart

**Comment by mikeS7** [comment]
@bartbutenaers ,
Please add or replace with something like:
To use node-red-contrib-vcgencmd in docker a custom image should be used.
Sample Dockerfile to build custom image:
```
FROM nodered/node-red

USER    root
RUN     apk add --no-cache raspberrypi
USER    node-red
```

and container should be run the following way:
`docker run ... --device=/dev/vchiq -e LD_LIBRARY_PATH=/opt/vc/lib`

**Comment by bartbutenaers** [comment]
@TheNON75, 
Could you please let us know whether Mike's info is enough to get you up and running.
If so, I will add the info to the readme page.
Thanks to the both of you!!

**Comment by TheNON75** [comment]
hi @bartbutenaers, thanks, checking in a moment

UPDATE:
as I am not aware how to build a custom image, I could follow in 1 to 1. The steps I took for testing:
- docker run with adding (obviously without the leading tailing dots)  `--device=/dev/vchiq -e LD_LIBRARY_PATH=/opt/vc/lib`
- docker exec -it containername /bin/bash
- sudo, then ran the `run  apk add --no-cache raspberrypi` command with success 
- docker restart containername

Results:
- received in node red the following error: VCHI initialization failed
- the device /dev/vchiq is visible within docker
- running the command `/usr/src/nvcgencmd measure_temp` in /bin/bash fails, no such file or directory
- running the above command in bash after sudoing is successful: `temp=59.1'C`

So there must be some privilege related issues
