### ISSUE TITLE
path on RedMatic/RaspberryMatic is different

### ISSUE THREAD

**Issue by fablable** [bartbutenaers/node-red-contrib-vcgencmd#3]
RedMatic is a Node-RED add-on for the RaspberryMatic home automation system. While this is running on a Raspberry Pi, it is not based on Raspbian OS. In this particular environment, the path to vcgencmd is actually /usr/bin/vcgencmd

I made it work for me by modifying this.fullPath in vcgencmd.js. Maybe a config option would be a more general solution, though.

Thank you very much  for developing this node and providing it to the community!

**Comment by bartbutenaers** [comment]
Hi @fablable,

I have added it to my Github repository, and would be nice if you could test it (so I can publish it afterwards on NPM).  You can install it (version **1.0.3**) from Github like this:
```
npm install bartbutenaers/node-red-contrib-vcgencmd
```

The path is now available in the config screen:

![image](https://user-images.githubusercontent.com/14224149/71783304-33206a00-2fe5-11ea-95b6-b4ded83d47db.png)

For existing nodes, by default "/opt/vc/bin/vcgencmd" will be used.

When an non-existing path is specified, this will be reflected in the node status:

![image](https://user-images.githubusercontent.com/14224149/71783310-5814dd00-2fe5-11ea-8c6e-df78951307ed.png)

Hope to hear from you soon!
Bart

**Comment by fablable** [comment]
Works beautifully for me!
HomeMatic / RaspberryMatic / RedMatic users will greatly appreciate that.
Thanks for implementing the feature in no time!

**Comment by bartbutenaers** [comment]
Hi, thanks for your feedback!
Version **1.0.3** has been published on npm.
