### ISSUE TITLE
Changing path to a raspberrypi in a LAN

### ISSUE THREAD

**Issue by Robi1010MD** [bartbutenaers/node-red-contrib-vcgencmd#4]
Hi,

is it possible to get a functional path to a raspberrypi in a LAN to control vcgencmd? Thx for your help.

Kind regards from Germany

**Comment by bartbutenaers** [comment]
Hi @Robi1010MD,
Sorry for the delay, but had surgery and recovery took a bit longer as expected...
Do I understand your question correctly: do you want to trigger the vcgencmd remotely from another computer, and get a result back there?  Or do you mean something else?
Think I will need some more detailed information to help you with your question.
Greetings from Belgium,
Bart

**Comment by Robi1010MD** [comment]
Hi @bartbutenaers 

thx for your answer. 👍 
Yes i want to trigger the vcgencmd remotely. Node-red runs on a windows pc and i want to trigger a raspberry pi in my network. 

Robert

**Comment by bartbutenaers** [comment]
Morning,
unfortunately I cannot execute a linux command on your Raspberry, started from Node-RED on your Windows pc.

I assume the only option is to _**install Node-RED on your Raspberry**_, which is very easy to setup (only a [single ](https://nodered.org/docs/getting-started/raspberrypi) command).  Then you can run my vcgencmd node in Node-RED on your Raspberry...

And then you can easily communicate between all your Node-RED systems in your house via MQTT messages, by installing an MQTT broker.  which is also easy to setup on your Raspberry (as described [here](https://randomnerdtutorials.com/how-to-install-mosquitto-broker-on-raspberry-pi/)).

Via the mqtt-in and mqtt-out nodes of Node-RED you then easily can send whatever you want.
For example:

![image](https://user-images.githubusercontent.com/14224149/77222016-984d1b80-6b4f-11ea-9402-29242a927ab8.png)

Think that is the only way...

P.S. it is better to ask such kind of questions next time on the Node-RED forum.  Then you will get much more feedback, and then others can learn from it.

Bart

**Comment by Robi1010MD** [comment]
Hi @bartbutenaers ,
i will try it out. I'm new to node-red and i didn't know where to ask. So thank you for your help. :)

Robert

**Comment by bartbutenaers** [comment]
Good luck then :+1:

**Comment by bartbutenaers** [comment]
Or if you just need a simple setup, perhaps you don't need a node-red installation on your portable?  Just install node-red on your raspberry, and you can navigate to the flow editor from your windows portable via your browser...
